name: Python package

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: brew uninstall libomp
      if: matrix.os == 'macos-11'
      run: |
        brew uninstall --ignore-dependencies libomp

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.8.1
      env:
        CIBW_ARCHS_MACOS: x86_64 universal2 arm64
        CIBW_ARCHS_LINUX: x86_64 i686

    - name: Show files
      run: ls -lh wheelhouse
      shell: bash

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl
